language: python
# sudo: false
cache: pip
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    CFLAGS="-O0"

matrix:
  include:
    - env: TOXENV=check
    - env: TOXENV=3.4
    - env: TOXENV=3.5
      addons:
        apt:
          sources:
          - deadsnakes
          packages:
          - python3.5
          - python3.5-dev
    - env: TOXENV=3.6

before_install:
  - env
install:
  - pip install tox coveralls
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - pip install -r test_requirements.txt
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
after_success:
  - coveralls
  - coverage xml
  # - python-codacy-coverage -r coverage.xml
notifications:
  email:
    on_success: never
    on_failure: always
